mysql:
  db_name: returnable_robot
  host: 192.168.8.93
  port: 32578
  user: root
  password: XMlianluoyimysql!!!

pre_package: cn.xmlly.returnablerobot.
base_page: cn.xmlly.common
title: wechat_api
path: D:/temp/python/